import { DriverProfile, EmergencyDispatch, Invoice } from './types';

export const MOCK_OWNER = {
  fullName: "Rajesh Sharma",
  vpa: "rajesh@okhdfcbank",
  company: "Fleet Logistics Ltd • South Hub",
  fleetSize: 14,
  assignedDrivers: 11,
  credits: 18450,
  avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAiXNNDtVIxy4oXAxPUF4158y09HWqvv5ZVQrjBQXNKFWRLf8ajtqLKydYVMnXVqoR3plcnNQW9nukTCgoDGHSdP9ovsJbGOpjbqRmVZf-PCsEK9kzQ74gMP2v2YZ2WgmPa5gn71ZyKZERxuknSfkd7q1niBqDiSAwX3zl4FrnOhpv1_EoUuR9_qvS56GGN1KaFFciK2HPT9J5yezxv-vjq7jPpBxFvI3U2Q2k0Pim3aPqevJ0UN4jrUw",
};

export const MOCK_DRIVERS: DriverProfile[] = [
  {
    id: "drv_1",
    fullName: "Rajesh Verma",
    phoneNumber: "+91 94480 12345",
    role: "driver",
    licenseCategory: ["LMV", "HMV"],
    experienceYears: 9,
    hourlyRate: 150,
    dailyRate: 1100,
    currentStatus: "online",
    aadhaarStatus: "verified",
    licenseNumber: "DL-MH02-2016-99201",
    badgeNumber: "BADGE-HMV-8820",
    dob: "12/08/1986",
    gender: "Male",
    averageRating: 4.92,
    totalReviews: 124,
    isAiAgent: false,
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDSnZdZ7tDXqYJQ7zbWg2V0GP9KCdYEz6xJCkqQ2Y7D9hbx8QWfvlijQ36N2jqcVOsXWfoltwI6x0BXdifQX9PTqu-Zh4pCH7oVm_RUTvxuDBRXm5Y6z5X0nB4Ndh8HoDvYu6uaSQAuxXTj3nc5JMFDyVik-fb19ygiCpVXeo_qeCbP3t5RPUUxJu-KisAHkuZnIaouCKUq0KiKs-owIRe1XaeJTSZqBXgYK2f0M26g344t66bJA31zeA",
    avatarAlt: "Portrait of professional Indian transport driver Rajesh Verma",
    location: {
      lat: 12.9716,
      lng: 77.5946,
      address: "Indiranagar, Bengaluru, KA"
    },
    qualifiedVehicles: ["Tata Prima 4028", "Ashok Leyland 2820 Tipper", "Toyota Innova HyCross"],
    medicalFitness: "Grade A • Eye 6/6",
    policeClearance: "No Pending Cases (Cleared CCTNS)"
  },
  {
    id: "drv_2",
    fullName: "Vikram Singh",
    phoneNumber: "+91 98450 22104",
    role: "driver",
    licenseCategory: ["HEMM", "HMV"],
    experienceYears: 11,
    hourlyRate: 180,
    dailyRate: 1200,
    currentStatus: "online",
    aadhaarStatus: "verified",
    licenseNumber: "DL-KA04-2013-09884",
    badgeNumber: "HEMM-MINING-449",
    dob: "24/09/1988",
    gender: "Male",
    averageRating: 4.96,
    totalReviews: 182,
    isAiAgent: false,
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAwuyUG9hiicbUUvgFpgG9NK-ELHS9sRUYswN5ssotsIYCgtMJZFM1g5vjAMh61EEL6XYV_-TsmWH1XapNAoLD2i4aXTKL08lXwjWOXfLcLHkThykhM2ls3KMyOgQQ1QQumwX4oOK1RDOdukjtyHqwWx67YLPXzEqMJ2-NjcKdIEFb7EN0vXDUmAByb09TXXDDEceir5JN8OI-0xSZBag8QkvRiXHNqlRegN5wKitNnY47owQfceGw6rw",
    avatarAlt: "Portrait of heavy excavation operator Vikram Singh",
    location: {
      lat: 12.9815,
      lng: 77.6044,
      address: "Koramangala 4th Block, Bengaluru, KA"
    },
    qualifiedVehicles: ["CAT 320D Excavator", "Komatsu PC210-10", "JCB 3DX EcoXcellence", "Tata Signa 4825.TK Tipper"],
    medicalFitness: "Grade A • Biometric Approved",
    policeClearance: "No Record Found (Cleared CCTNS)"
  },
  {
    id: "drv_3",
    fullName: "Ananya Roy",
    phoneNumber: "+91 97412 88452",
    role: "driver",
    licenseCategory: ["LMV"],
    experienceYears: 7,
    hourlyRate: 120,
    dailyRate: 950,
    currentStatus: "online",
    aadhaarStatus: "verified",
    licenseNumber: "DL-KA03-2017-04812",
    badgeNumber: "VIP-CHAUFFEUR-992",
    dob: "11/11/1993",
    gender: "Female",
    averageRating: 4.98,
    totalReviews: 310,
    isAiAgent: false,
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCMx3ilPozSUFWTwMdT4fvzlK-A9qW-kg7fBHphZbpqpF5GrXQ3yBNJCle92vNDof77e5KyIQts0UXr_bqApzUnVQ_1HHKHsIhRpu_ArpiSSEmWeaODpej-ZGlj1CNUEnfrhb_gJCnsQ-ky7b9OcylYCsOQw7jYxLTUBIBjL5wJN1R5KD1NhLwacvE4JLC2ZbOBPjMUUeYpt06cARQT84JwP_vvtXiyqMqVsKrcbVDNiTltRi6HiQjiDA",
    avatarAlt: "Chauffeur portrait Ananya Roy",
    location: {
      lat: 12.9620,
      lng: 77.5850,
      address: "Indiranagar Corridor, Bengaluru, KA"
    },
    qualifiedVehicles: ["Mercedes-Benz E-Class", "BMW iX xDrive50", "Tesla Model Y ADAS", "Toyota Innova HyCross VIP"],
    medicalFitness: "Grade A • Perfect 6/6 Vision",
    policeClearance: "Zero Infractions (NOC Active)"
  },
  {
    id: "drv_4",
    fullName: "Marcus Vance",
    phoneNumber: "+91 99000 81234",
    role: "driver",
    licenseCategory: ["PILOT"],
    experienceYears: 18,
    hourlyRate: 1500,
    dailyRate: 12000,
    currentStatus: "acting",
    aadhaarStatus: "verified",
    licenseNumber: "DGCA-ATPL-98214-IN",
    badgeNumber: "PILOT-ATPL-982",
    dob: "27/02/1982",
    gender: "Male",
    averageRating: 5.00,
    totalReviews: 89,
    isAiAgent: false,
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAsSBqBjrXXi_wbGJQkWqlTPXRHyzs3RQ-V83Q3dmdMdSHhIX21m4AQPPs9V3BhKXnIpIvpsA4KH2jXlrocB9ohtAVedhECuw_c8_EuQjH5jvZCx8w5X4vUeaK3Y60psNzL0xjfxXwwI9DUh_RFL5H9xtzGbFA7rfbJn9AfVa5Mv9xoC4y3DmbskVl7SooBR8dbCuaQ9otUR7-ibs1KD08DTVvN6OhZ9jHFI6qoBsyzqMMCOnoK1_KLiA",
    avatarAlt: "Aviation Captain Marcus Vance",
    location: {
      lat: 12.9902,
      lng: 77.6210,
      address: "Indiranagar Enclave, Bengaluru, KA"
    },
    qualifiedVehicles: ["Boeing 737 Max", "Airbus A320neo", "Bell 407 Helicopter", "Gulfstream G650"],
    medicalFitness: "DGCA Class 1 Medical Clear (Valid)",
    policeClearance: "Verified Global Record Sync"
  },
  {
    id: "drv_5",
    fullName: "Sandeep K. Yadav",
    phoneNumber: "+91 88720 94112",
    role: "driver",
    licenseCategory: ["HEMM"],
    experienceYears: 8,
    hourlyRate: 160,
    dailyRate: 1100,
    currentStatus: "offline",
    aadhaarStatus: "pending",
    licenseNumber: "DGMS-MIN-2019-4402",
    badgeNumber: "HEMM-EXCAVATOR-110",
    dob: "04/11/1991",
    gender: "Male",
    averageRating: 4.88,
    totalReviews: 64,
    isAiAgent: false,
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCxhBdgcvWG9UNJvKMke-G3sqx2ZXYuZW2wbo2jETEA_lMnfIVmqu_DSGChNR5YpeST3SyrzwIPyTmW6yhihY_ISnbH8A9aoYHqpoeT2ISeOfweb72WJkSe-onlGVDhU4iGpH2BieczvFSiGYlqJurE4Ag5n6BneDeKWoCIa67WTjKI4tcVb5YR-JG3QsTPZjiLrg3f_Os6G8YViww4gFL6yU1LCzkgFd-8s_9OSXGsi4SlatjYi7aESQ",
    avatarAlt: "Mining Machinery Operator Sandeep Yadav",
    location: {
      lat: 12.9510,
      lng: 77.6110,
      address: "Bhiwandi Area, Mumbai, MH"
    },
    qualifiedVehicles: ["Caterpillar 320D", "HEMM Dump Truck", "Komatsu PC300"],
    medicalFitness: "In Review (Biometrics Queue)",
    policeClearance: "Awaiting State UIDAI Sync"
  },
  {
    id: "drv_6",
    fullName: "Sunil Patil",
    phoneNumber: "+91 97321 00481",
    role: "driver",
    licenseCategory: ["LMV"],
    experienceYears: 5,
    hourlyRate: 110,
    dailyRate: 850,
    currentStatus: "acting",
    aadhaarStatus: "verified",
    licenseNumber: "DL-MH01-2019-00124",
    badgeNumber: "NIGHT-CHAUFFEUR-004",
    dob: "19/06/1994",
    gender: "Male",
    averageRating: 4.90,
    totalReviews: 98,
    isAiAgent: false,
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDsa9g73cXlcmhrBrE4XrczRQ6e1Hp_fP8CVE2Rx0R0R3QtOt0mbSzcghZsq2O-ieQFtv_H-tgD9aUuk7JXrkkXVnBjDlMB_vbqcp3-N-C_6uWUR2GRvvOvIkEXjfNu7GdEwautAjl3jYm6lHVW7Fr0n6QWqpoYdG9OLjBpmIsqAlRUI3LUz7qzGFtWeLExjvG2teLxyCOTf0dFJYte8v4yUBS58k50IbMj9ZBJpdVkl0XpQYP67IipQg",
    avatarAlt: "Executive chauffeur Sunil Patil",
    location: {
      lat: 12.9678,
      lng: 77.5992,
      address: "Koramangala, Bengaluru, KA"
    },
    qualifiedVehicles: ["Mercedes E-Class", "Audi A6", "Jaguar XF", "Tata Nexon EV"],
    medicalFitness: "Grade A • Zero Night-blindness certified",
    policeClearance: "Zero Incidents Recorded"
  },
  {
    id: "drv_7",
    fullName: "CyberMotion Fleet-Node #042",
    phoneNumber: "+91 90000 00042",
    role: "driver",
    licenseCategory: ["HMV", "HEMM"],
    experienceYears: 4,
    hourlyRate: 350,
    dailyRate: 2800,
    currentStatus: "online",
    aadhaarStatus: "verified",
    licenseNumber: "ARAI-ADS-2025-DP09",
    badgeNumber: "TELE-OP-NODE-42",
    dob: "Calibrated 2025",
    gender: "AI Automated Node",
    averageRating: 4.99,
    totalReviews: 842,
    isAiAgent: true,
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAM5gRa14Sq5pzaGfHzF03HvkzuL_YbpwRIyBic0mD83EFBgrCMpfa-hK2PF6xRdUDkSBi4VyfthZXWrC2sUeo2W51NAsjzWp-LucrflhQOJOQ2PmyoANIkT6XjV87F768eczZZSjMpZOvkXr0wcB-QnChi_94_3-X40LDWbUTtFNHGbMPd0LoIK8lLUFlESUcLLHyr28tKUpEr_SNNeLgOeJHszV25xuSsxY0H4Y0w-9W6_Ze0sGg0Ug",
    avatarAlt: "Autonomous AI Fleet-Node Agent",
    location: {
      lat: 12.9789,
      lng: 77.5891,
      address: "Bhiwandi Yard Core-4, Mumbai, MH"
    },
    qualifiedVehicles: ["Hesai 128-Beam LiDAR", "Dual 5G Teleoperated Yard Tugger", "Tata Prima EV Autonomous Tug"],
    medicalFitness: "Fail-Safe Override: Active • Calibrated",
    policeClearance: "ISO 26262 Functional Safety Compliant"
  }
];

export const MOCK_DISPATCHES: EmergencyDispatch[] = [
  {
    id: "DP-8924",
    title: "Urgent Tipper Driver (25T Mining Quarry)",
    vehicle: "Ashok Leyland 2820 Tipper (Heavy Hauler)",
    origin: "Kolar Stone Basin #3",
    destination: "Bengaluru East Infrastructure Terminal",
    payout: 2200,
    status: "broadcasting",
    timestamp: "04m 18s ago",
    matchedDriversCount: 48,
    respondingDrivers: [
      {
        id: "resp_1",
        fullName: "Ramesh Kumar",
        phoneNumber: "+91 94110 99824",
        role: "driver",
        licenseCategory: ["HMV"],
        experienceYears: 12,
        hourlyRate: 160,
        dailyRate: 1300,
        currentStatus: "online",
        aadhaarStatus: "verified",
        licenseNumber: "DL-KA02-2012-09224",
        dob: "14/05/1982",
        gender: "Male",
        averageRating: 4.90,
        totalReviews: 342,
        isAiAgent: false,
        avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuANyAzKkLP3uBJ7h58VFV2hae40ZIBGn39kzByJq7HmZWnHYHscGqIDGyz-tCXxiBwp4HWqz4LsHpJMQGe7NvLN4Lh_yxMtfTCgLu8e6krJKFXFMsBa7aaNWEg3sHZN2c1xcL9HT2yFObstpBdPRIFIFjqvYyoOEj_uO6oVT6cbNZ9z0q2tUDkxXT38EUQxnyi2kcIgRI60gHLMVvEaQWYxEQ4ciPpWW9-J4XlkFkl9TEh_dhntNJxjXA",
        avatarAlt: "Tipper Driver Ramesh Kumar",
        location: {
          lat: 12.9734,
          lng: 77.5921,
          address: "Indiranagar Depot"
        },
        qualifiedVehicles: ["Ashok Leyland Tipper", "Tata Signa Tipper"],
        medicalFitness: "Grade A • Eye 6/6",
        policeClearance: "No cases pending"
      },
      {
        id: "resp_2",
        fullName: "Gurpreet Singh",
        phoneNumber: "+91 97201 44101",
        role: "driver",
        licenseCategory: ["HMV"],
        experienceYears: 14,
        hourlyRate: 190,
        dailyRate: 1500,
        currentStatus: "online",
        aadhaarStatus: "verified",
        licenseNumber: "DL-PB11-2010-00441",
        dob: "02/10/1980",
        gender: "Male",
        averageRating: 4.80,
        totalReviews: 189,
        isAiAgent: false,
        avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCzpgMQEl3XGkZX6C4lvLo4MuBGvLgY40Sq9USIPJjoIi6BQKj60I5u5f0WH0iYA1mdivKkySXt-tAcWzAyqxLiLkC9PqA5mHToC1qrQ9jnkXNbp-DJTN2bexspUikKakExHbhJJFy4go9gWdp84FL4fttj1Qz5bSABoUT34vYisywRLPrHDI8UyJYMs0q-OjwbNYT4hkn8cftOi_IreZougrYJhQQQiys4rZWS2I_eQLCQwwH4--3hHw",
        avatarAlt: "Gurpreet Singh",
        location: {
          lat: 12.9790,
          lng: 77.5999,
          address: "Koramangala 1st Block"
        },
        qualifiedVehicles: ["Multi-axle Trailer", "Tata Prima 4028"],
        medicalFitness: "Grade A • Satisfactory",
        policeClearance: "No criminal records"
      }
    ]
  },
  {
    id: "DP-8810",
    title: "Emergency Night LMV Chauffeur",
    vehicle: "Mercedes E-Class (Executive Sedan)",
    origin: "Koramangala 4th Block",
    destination: "Kempegowda Int'l Airport Terminal 2",
    payout: 950,
    status: "active",
    timestamp: "12m 30s ago",
    matchedDriversCount: 14,
    respondingDrivers: [],
    assignedDriver: {
      id: "drv_6",
      fullName: "Sunil Patil",
      phoneNumber: "+91 97321 00481",
      role: "driver",
      licenseCategory: ["LMV"],
      experienceYears: 5,
      hourlyRate: 110,
      dailyRate: 850,
      currentStatus: "acting",
      aadhaarStatus: "verified",
      licenseNumber: "DL-MH01-2019-00124",
      badgeNumber: "NIGHT-CHAUFFEUR-004",
      dob: "19/06/1994",
      gender: "Male",
      averageRating: 4.90,
      totalReviews: 98,
      isAiAgent: false,
      avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDsa9g73cXlcmhrBrE4XrczRQ6e1Hp_fP8CVE2Rx0R0R3QtOt0mbSzcghZsq2O-ieQFtv_H-tgD9aUuk7JXrkkXVnBjDlMB_vbqcp3-N-C_6uWUR2GRvvOvIkEXjfNu7GdEwautAjl3jYm6lHVW7Fr0n6QWqpoYdG9OLjBpmIsqAlRUI3LUz7qzGFtWeLExjvG2teLxyCOTf0dFJYte8v4yUBS58k50IbMj9ZBJpdVkl0XpQYP67IipQg",
      avatarAlt: "Executive chauffeur Sunil Patil",
      location: {
        lat: 12.9678,
        lng: 77.5992,
        address: "Koramangala, Bengaluru, KA"
      },
      qualifiedVehicles: ["Mercedes E-Class", "Audi A6", "Jaguar XF", "Tata Nexon EV"],
      medicalFitness: "Grade A • Zero Night-blindness certified",
      policeClearance: "Zero Incidents Recorded"
    }
  }
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "INV-2025-081",
    plan: "Fleet Pro Monthly",
    type: "Recurring Mandate",
    date: "04 Mar 2025, 08:30 IST",
    vpa: "rajesh@okhdfcbank",
    paymentId: "pay_Q8l39sPz901",
    amount: 1499.00,
    status: "PAID"
  },
  {
    id: "INV-2025-044",
    plan: "Daily Quick Pass",
    type: "Ad-Hoc Unlocks",
    date: "18 Feb 2025, 14:15 IST",
    vpa: "rajesh@okhdfcbank",
    paymentId: "pay_P1m24vKx482",
    amount: 199.00,
    status: "PAID"
  },
  {
    id: "INV-2025-012",
    plan: "Fleet Pro Monthly",
    type: "Recurring Mandate",
    date: "04 Feb 2025, 08:30 IST",
    vpa: "rajesh@okhdfcbank",
    paymentId: "pay_N9k87mJx119",
    amount: 1499.00,
    status: "PAID"
  }
];
